# Generated by Django 4.0.2 on 2022-02-06 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bday',
            old_name='confession',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='bday',
            old_name='title',
            new_name='name',
        ),
    ]
