# Generated by Django 4.0.2 on 2022-02-06 08:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_confession_bday_email_rename_title_bday_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='bday',
            name='bday',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bday',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
